# creation of pods using yml file

# Required fields:-

# apiVersion:version of k8s api using to create objects (e.g. v1(for pods),apps/v1Beta etc)

# kind:it can take values as follows
# Pod->v1
# Service->v1
# ReplicaSet->apps/v1
# Deployment->apps/v1

# metadate: it contains information about the pod like name etc, it is a dictionery,
#           labels can have any key value pairs as needed

# spec: depending on the type of object (pod in this case) we are trying to make
# we provide extra info in specs it is a dictionery which expects a lsit of containers
# containerPort: specifing this creates the required networking mappings and expose this port for external traffic

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx
  labels:
    env: prod
    type: pod
spec:
  containers:
    - name: ngnx
      image: nginx:latest #write the name of the image as in docker repo
      ports:
        - containerPort: 80 # if we don't specify this it assumes 80 as default bcz of internal config but we will not be able to access this pod from outside cluster
